### ISSUE TITLE
'Config' object has no attribute 'define_bool_state'

### ISSUE THREAD

**Issue by aliaclarkelsayed** [patrickbryant1/Umol#23]
After running the following as in the test example:
`conda activate umol
bash predict.sh`

I got the following error from configurations.py: 
AttributeError: 'Config' object has no attribute 'define_bool_state'

**Comment by patrickbryant1** [comment]
Maybe call the commands separately? Are you sure you installed the env?

**Comment by he-hai** [comment]
I got the same error raised when running `predict.py` from the script. Not sure if it's from the compatibility problem of `jax` and `flax` https://github.com/google/flax/issues/3180

Could you @patrickbryant1 specify your final working version of `jax` and `flax`? I would like to try using the same version. I'm using Cuda 12.2 btw if relevant 


But for sure, `pip install --upgrade numpy` in `install_dependencies.sh` gave me error since `numpy 2` just released.

**Comment by patrickbryant1** [comment]
Hi,

Maybe see some of the other errors/look in the env for the versions. FLAX is not used so idk if this is causing your issues?

I see, we will check the new versions and provide a new env in a couple of weeks. 

Best,

Patrick

**Comment by he-hai** [comment]
Hi, good to know flax is not used. Because it is listed in the environment.yml?

**Comment by L-Hai** [comment]
> I got the same error raised when running `predict.py` from the script. Not sure if it's from the compatibility problem of `jax` and `flax` [google/flax#3180](https://github.com/google/flax/issues/3180)
> 
> Could you @patrickbryant1 specify your final working version of `jax` and `flax`? I would like to try using the same version. I'm using Cuda 12.2 btw if relevant
> 
> But for sure, `pip install --upgrade numpy` in `install_dependencies.sh` gave me error since `numpy 2` just released.

I solved my problem by downgrading jax to 0.4.23.

**Comment by patrickbryant1** [comment]
Great 👍 yeah, sorry about these issues. The versions change constantly and it's hard to keep up. We have tried to distribute with images but then you get other issues.
