### ISSUE TITLE
Predict ligand positions for large protein by multiple GPUs 

### ISSUE THREAD

**Issue by whl-git** [patrickbryant1/Umol#28]
Hi,

I am trying to predict ligand positions for a protein with around 700 residues, but get the error below:
 XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17608450984 bytes (17.6GB).

I checked the 'predict.sh' and realized it was due to the out of memory when executing './src/prediction.py'. In fact, there are 4 RTX 4070 ti super GPUs (16GB ram each) in my machine and I wonder if I can allocate memory to multiple GPUs so that I can get enough memory  for my prediction work. Many thanks.

**Comment by patrickbryant1** [comment]
Hi, 

No you can't devide predictions between gpus. This is because the matrix multiplication can't be split between processors automatically. Maybe you can write instructions for this, but it's not trivial. Try to get a bigger gpu os crop the sequence and run e.g. 2 preds of size 350/an overlap scheme.

Best,

Patrick
