### ISSUE TITLE
About the FAPE loss

### ISSUE THREAD

**Issue by fuxuliu** [patrickbryant1/Umol#33]
Hi, Patrick.

I have a question abouth fape loss of umol, The article mentioned: “The FAPE is calculated using only The amino acid N - CA - C frames forward ligand atoms as well.”
I don't quite understand the meaning of this paragraph, is it right to exclude ligand atom when calculating fape loss, and only use the frame formed by the three atoms of protein amino acid N-CA-C for calculation?

**Comment by patrickbryant1** [comment]
Hi,

Since a consistent frame can't be formed from the ligands due to the varying atom orders/types there are two options: 1. Select a random set of atoms and set these as the ligand frame(s) or 2. Don't use ligand frames. The ligand atoms are still used in FAPE, but seen only from the protein's point of view. The protein is never seen from the ligand's point of view. Since the ligand is much smaller and incorporated in the protein view (and pairwise loss), this has a small effect on the overall FAPE.

**Comment by fuxuliu** [comment]
Hi,

Thank you very much for your reply. 
From the perspective of code, when you calculate backbone loss, you use n-ca-c to calculate gt_affine. However, ligand assumes that there is only one atomic coordinate of ca, so how are the other two coordinates defined? It's the coordinates of these two atoms, n and c, n_xyz=batch['atom14_gt_positions'][:,0,:], c_xyz=batch['atom14_gt_positions'][:,2,:])
```
#Get quat_affine for pseudo beta - modified!
  rot, trans = quat_affine.make_transform_from_reference(n_xyz=batch['atom14_gt_positions'][:,0,:],
                                                        ca_xyz=batch['atom14_gt_positions'][:,1,:],
                                                        c_xyz=batch['atom14_gt_positions'][:,2,:])
  gt_affine = quat_affine.QuatAffine(
        quaternion=quat_affine.rot_to_quat(rot, unstack_inputs=True),
        translation=trans,
        rotation=rot,
        unstack_inputs=True)
```

**Comment by patrickbryant1** [comment]
Hi,

As I tried to explain above, FAPE is not used from the ligand's point of view. Try to think about FAPE as the average error looking from each residue. The ligand's position will be evaluated from the viewpoint of each residue, but the residue positions will not be evaluated from the viewpoint of the ligand.

Best,

Patrick
